config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :projectts
  # get "bug", to: "bugs#new"

  # resources :bugs do
  #   get :feature, on: :member
  #   get :bug, on: :member
  # end
  get "bugs/:id/bug", to: "bugs#bug", as: :bug_bug
  get "bugs/:id/feature", to: "bugs#feature", as: :feature_bug
  get "bugs/:id/new", to: "bugs#new", as: :bug_new
  post "bugs", to: "bugs#create"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "home#index"
end

app/models/projectt.rb
class Projectt < ApplicationRecord
  validates :title, presence: true, length: { minimum: 5, maximum: 50 }
  validates :description, presence: true, length: { minimum: 5, maximum: 50 }

  has_many :bugs , :dependent => :destroy

  belongs_to :manager, class_name: "User"
  belongs_to :developer, class_name: "User"

  belongs_to :qa, class_name: "User"
end

app/controllers/projectts_controller.rb
class ProjecttsController < ApplicationController
  load_and_authorize_resource

  def new
    @projectt = Projectt.new
    # @user = User.all
  end

  def create
    @projectt = Projectt.new(projectt_params)

    # @projectt.developer_id = params[:projectt][:user][:dev_id]
    # @projectt.qa_id = params[:projectt][:user][:qa_id]
    @projectt.manager_id = current_user.id

    if @projectt.save
      redirect_to root_path
    end
  end

  def edit
    @projectt = Projectt.find(params[:id])
  end

  def update
    @projectt = Projectt.find(params[:id])

    if @projectt.update(params_projectt)
      redirect_to root_path
    end
  end

  def index
    @projectts = Projectt.all
  end

  def show
    @projectt = Projectt.find(params[:id])
  end

  def destroy
    @projectt = Projectt.find(params[:id])
    if @projectt.destroy
      flash[:success] = "Object was successfully deleted."
      redirect_to root_path
    else
      flash[:error] = "Something went wrong"
      redirect_to projectts_path
    end
  end

  private

  def projectt_params
    params.require(:projectt).permit(:title, :description, :developer_id, :qa_id)
  end
end

app/views/projectts/bug.html.erb
<table>
<tr>
<th>Title of Bug</th>
<th>Description</th>
</tr>
<% @bug.each do |b| %>
<tr>

<td><%= b.title %> <br></td>
<td><%= b.description %> <br></td>
<td><%= b.deadline %></td>
<% end %>

</tr>
</table>

app/views/projectts/edit.html.erb
<h2>Project Edit Page</h2>
<%= form_for @projectt do |f| %>
<p>
  <%= f.label :title %>
  <br />
  <%= f.text_field :title %><br />
</p>
<p>
  <%= f.label :description %><br />
  <%= f.text_area :description %>
</p>
<h3>Developer</h3>
<%= f.select :developer_id, User.all.developer.collect {|p| [ p.name, p.id ] }%>

<h3>Qa</h3>
<%= f.select :qa_id, User.all.qa.collect {|p| [ p.name, p.id ] } %>

<p><%= f.submit %></p>

<% end %>

app/views/projectts/index.html.erb
<table>
  <tr>
    <th>Title</th>
    <th>Description</th>
    <th>Manager</th>
    <th>Developer</th>
    <th>Qa</th>
    <th>Delete Project</th>
    <th>Show all Bugs</th>
    <th>Show all Features</th>
   
  </tr>
  <% @projectts.each do |p| %>
    <tr>
      <td><%= p.title %></td>
      <td><%= p.description %></td>
      <td><%= p.manager.name %></td>
      <td><%= p.developer.name %></td>
      <td><%= p.qa.name%></td>
      <td><%= link_to 'Show Project', projectt_path(p) %></td>
      <td>
        <%= button_to 'Delete' , projectt_path(p), method: :delete, data: {
      confirm: "are you sure"} %>
      </td>
      <td><%= link_to 'Show all bugs', bug_bug_path(p) %></td>
      <td> <%= link_to 'Show all features', feature_bug_path(p) %> </td>
     
       %>
    </tr>
  <% end %>
</table>
<% if user_signed_in? %>
  <% if current_user.user_type == "manager" %>
    <%= link_to 'Create new project ',
new_projectt_path %>
  <% end %>
<% end %>

app/views/projectts/new.html.erb
<%= form_with(model: @projectt, url: projectts_path) do |f| %>
<p>
  <%= f.label :title %>
  <br />
  <%= f.text_field :title %><br />
</p>
<p>
  <%= f.label :description %><br />
  <%= f.text_area :description %>
</p>

<h3>Developer</h3>
<%= f.select :developer_id, User.all.developer.collect {|p| [ p.name, p.id ] }%>

<h3>Qa</h3>
<%= f.select :qa_id, User.all.qa.collect {|p| [ p.name, p.id ] } %>

<p><%= f.submit %></p>

<% end %>

app/views/projectts/show.html.erb
Project Id:<%= @projectt.id %><br>
Project TiTle:<%= @projectt.title %><br>
Project Description:<%= @projectt.description %> <br>
Project Manager Name: <%= @projectt.manager.name %> <br>
Project Deleloper Name: <%= @projectt.developer.name %> <br>
Project Qa Name: <%= @projectt.qa.name %> <br>
<% if user_signed_in? %>
  <% if current_user.user_type == "qa" %>
    <%= link_to 'Add Bug', bug_new_path(@projectt) %>
  <% end %>
<% end %>