config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :projectts
  # get "bug", to: "bugs#new"

  # resources :bugs do
  #   get :feature, on: :member
  #   get :bug, on: :member
  # end
  get "bugs/:id/bug", to: "bugs#bug", as: :bug_bug
  get "bugs/:id/feature", to: "bugs#feature", as: :feature_bug
  get "bugs/:id/new", to: "bugs#new", as: :bug_new
  post "bugs", to: "bugs#create"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "home#index"
end

app/models/bug.rb
class Bug < ApplicationRecord
belongs_to :projectt
end

app/controllers/bugs_controller.rb
class BugsController < ApplicationController
  load_and_authorize_resource

  def new
    @bug = Bug.new
    @type = ["feature", "bug"]
  end

  def create
    @bug = Bug.new(bug_params)
    debugger
    project = Projectt.find(params[:bug][:projectt_id])
    project.bugs.each do |b|
      if b.types == "Bug"
        if b.title == params[:bug][:title]
          @bug.errors.add(:bug, :not_implemented, message: "Title of Bug already Included.Write differen Title")
          break
        end
      end
    end
    @projectt_id = params[:projectt_id]
    if @bug.errors.any?
      flash.notice = "Title of Bug already Included.Write different Bug Title"

      render "new"
    elsif @bug.save
      redirect_to root_path
    end
  end

  def feature
    @project = Projectt.find(params[:id])
    @bug = @project.bugs
  end

  def bug
    @project = Projectt.find(params[:id])
    @bug = @project.bugs
    # debugger
  end

  private

  def bug_params
    params.require(:bug).permit(:title, :description, :deadline, :projectt_id, :types, :statuses)
  end
end

app/views/bugs/bug.html.erb
<table>
<tr>
<th>Title of Bug</th>
<th>Description</th>
<th>Deadline</th>

</tr>
<% @bug.each do |b| %>
<tr>
 <% if b.types == "Bug"%>
<td><%= b.title %> <br></td>
<td><%= b.description %> <br></td>
<td><%= b.deadline %></td>
<% end %>
<% end %>
</tr>
</table>

app/views/bugs/feature.html.erb
<table>
<tr>
<th>Title of Feature</th>
<th>Description</th>
<th>Deadline</th>

</tr>
<% @bug.each do |b| %>
<tr>
 <% if b.types == "Feature"%>
<td><%= b.title %> <br></td>
<td><%= b.description %> <br></td>
<td><%= b.deadline %></td>
<% end %>
<% end %>
</tr>
</table>

app/views/bugs/new.html.erb
      <%= javascript_include_tag :dropdown %>

      <% if notice %>
      <%= notice %>
      <% end %>

<%= form_with(model: @bug, url: bugs_path) do |b| %>
<p>
  <%= b.label :'Title of Bug'%>
  <br />
  <%= b.text_field :title %>
</p>
<p>
  <%= b.label :'Description of Bug'%>
  <br />
  <%= b.text_area :description %>
</p>
<p>
  <%= b.label :'Select Bug Date'%> <br>
  <%= b.date_field :deadline %>
  <br />
  </p>
  
  <p>
    <!-- <%= b.label :'Select Bug or Feature' %> <br> -->
    <%= b.select :types, [["Bug", "Bug"], ["Feature", "Feature"]],{prompt: "Select Type"}, {onchange: 'getType();'} %>
  </p>
  <p>
    <%= b.select :statuses, [], {prompt: "Select Status"} %>
  </p>
  </div>
  <p>
  <%= b.hidden_field :projectt_id, value: params[:id] %> 
  <%= b.submit 'Submit Bug' %>
</p>

<% end %>